adventureapp/urls.py
from django.urls import path
from . import views

app_name = "adventureapp"

urlpatterns = [
    path('',views.homepage,name='homepage'),
    path('rightpath/',views.rigthpath,name='rightpath'),
    path('leftpath/',views.leftpath,name='leftpath'),
    path('blue/',views.blue,name='blue'),
    path('green/',views.green,name='green'),
    path('safe/',views.safe,name='safe'),
    path('open/',views.open,name='open'),
    path('close/',views.close,name='close'),
    path('forest/',views.forest,name='forest'),
    path('park/',views.park,name='park'),
    path('safeopen/',views.safeopen,name='safeopen'),
    path('safepark/',views.safepark,name='safepark'),
    path('bad/',views.bad,name='bad'),
    path('line/',views.line,name='line'),
    path('go/',views.go,name='go'),
    path('going/',views.going,name='going'),
    path('neck/',views.neck,name='neck'),
    path('back/',views.back,name='back'),
    path('love/',views.love,name='love'),
    path('win/',views.win,name='win')
]

djangoadventure/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adventureapp.urls')),
]

adventureapp/models.py
from django.db import models

# Create your models here.

adventureapp/views.py
from django.shortcuts import render

# Create your views here.

def homepage(request):
    return render(request,'adventureapp/homepage.html')

def rigthpath(request):
    return render(request, 'adventureapp/rightpath.html')

def leftpath(request):
    return render(request, 'adventureapp/leftpath.html')

def blue(request):
    return render(request,'adventureapp/blue.html')

def green(request):
    return render(request,'adventureapp/green.html')

def safe(request):
    return render(request,'adventureapp/safe.html')

def open(request):
    return render(request,'adventureapp/open.html')

def close(request):
    return render(request,'adventureapp/close.html')

def forest(request):
    return render(request,'adventureapp/forest.html')

def park(request):
    return render(request,'adventureapp/park.html')

def safeopen(request):
    return render(request,'adventureapp/safeopen.html')

def safepark(request):
    return render(request,'adventureapp/safepark.html')

def bad(request):
    return render(request,'adventureapp/bad.html')

def line(request):
    return render(request,'adventureapp/line.html')

def go(request):
    return render(request,'adventureapp/go.html')

def going(request):
    return render(request,'adventureapp/going.html')

def neck(request):
    return render(request,'adventureapp/neck.html')

def back(request):
    return render(request,'adventureapp/back.html')

def love(request):
    return render(request,'adventureapp/love.html')

def win(request):
    return render(request,'adventureapp/win.html')

adventureapp/templates/adventureapp/blue.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="row">

    <div class="col"></div>
    <div class="col">
  
        <h1><strong>Secret World</strong></h1>
  
    </div>
    <div class="col">
  
      <h3><strong>Cüzdan : 25 Dinar</strong></h3>
  
    </div>
  
  </div>
  
  <br><br>

  <div class="card" style="width: 75rem; border-color: gold;">
    <div class="card-body">
      <h5 class="card-title">3. Bölüm</h5>
      <h5 class="card-title"><strong>Turnuva</strong></h5>
      <img src="{% static 'adventureapp/turnuva.jpg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
      <ol>
      <p class="card-text">Şehre gelen Katara hafif de olsa bir zırh almak istemişti ve 20 dinarlık hafif bir zırh aldı.</p>
      <p class="card-text">Bu şehirdeki turnuvada toplamda 32 kişiden oluşup 5 tur sürecektir.</p>
      <p class="card-text">Bu turnuvada bayılan , ölen veya sınır çizgisini geçen kişi kaybetmiş sayılacaktır ve kazanan ise her tur belli bir tutar ödül alacaktır.</p>
      <p class="card-text">1. olan kişi ise 20.000 dinar para ödülü alacaktır.</p>
      </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: gold;">
    <div class="card-body">
        <img src="{% static 'adventureapp/icekatana.jpeg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
        <ol>
      <p class="card-text">Bu turnuvada garanti çeyrek finale çıkacağı düşünülen toplam 6 kişi var.Bunlar arasında en göze çarpan kişi İzumi adında soğuk bakışlı bir kızdı.</p>
      <p class="card-text">İlk etapta Katara'nın karşısına zırhına güvenen biri vardı ama ağır zırhı yüzünden yavaş hareket edebilen birisiydi.</p>
      <p class="card-text">Katara hızlı bir şekilde bir yara verdiğinde ilk rakibi birden donmaya başladı ve Katara bu duruma inanamadı.</p>
      <p class="card-text">Bunu kılıcın gücü olduğunu anlayan Katara hızlı bir şekilde ilk turu geçti.</p>
      </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: gold;">
    <div class="card-body">
        <img src="{% static 'adventureapp/karşılaşmaiki.jpg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
        <ol>
      <p class="card-text">Katara ilk turdan sonra gece vakti kılıcına alışabilmek ve özelliğini anlamak için sıkı bir şekilde antrenman yapıyordu.</p>
      <p class="card-text">Katara'nın ikinci turdaki rakibi aynı Katara gibi hafif zırhlı ve kılıç kabiliyetine güvenen birisiydi.</p>
      <p class="card-text">Rakibi Katara'nın ilk etabını izlediği için sıyrık bile almamaya çalışıyordu ve Katara'nın hep boynunu hedefliyordu dolayısıyla bu durum bir hız testine dönmüştü.</p>
      <p class="card-text">Rakibi Katara'nın vuruşlarını iyi okumaya başlamış ve bunu kendi leyhine kullanıyordu.</p>
      <p class="card-text">Rakibi Katara'nın boynuna kılıcını daha da yaklaştırırken en sonunda kılıcı Katara'nın boynuna doğru geliyordu ve bunu anlayan Katara rakibinden uzaklaşmak isteyerek kılıcını savurduğunda kılıcı bir buzdan duvar yaparak rakibi sınır çizgisinden geçirmişti.</p>
      <p class="card-text">Ne olduğunu tam anlayamasa da kazanan Katara'ydı.</p>
      </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: gold;">
    <div class="card-body">
        <img src="{% static 'adventureapp/dost.jpg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
        <ol>
      <p class="card-text">İkinci turdan sonra dikkatleri üzerine yavaş yavaş çekmeye başlayan Katara durumundan oldukça memnundu.</p>
      <p class="card-text">Gece vakti yine antrenman yaparken yavaş yavaş bir gölgenin ona doğru geldiğini gördü ve biraz tedirgin oldu.</p>
      <p class="card-text">O gelen kişinin ikinci etapta yendiği rakibi olduğunu görünce biraz afallamıştı.</p>
      <p class="card-text">Rakibi adının Sai olduğunu ve birlikte antrenman yapmak istediğini söyleyince sebebini soran Katara'ya da onu yenen kişinin bu turnuvayı kazanması istediğini söylemişti.</p>
      <p class="card-text">Katara'da ne zararı olur diye düşünmüştü ve Sai de üstü açık bir antrenman merkezinde mi yoksa üstü kapalı bir antrenman merkezinde mi yapmak istediğini sordu.</p>
      </ol>
      <a href="{% url 'adventureapp:open' %}" class="btn btn-danger">Üstü Açık Antrenman Merkezi</a>
      <a href="{% url 'adventureapp:close' %}" class="btn btn-danger">Üstü Kapalı Antrenman Merkezi</a>
    </div>
  </div>

<br>

{% endblock %}

adventureapp/templates/adventureapp/green.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="row">

    <div class="col"></div>
    <div class="col">
  
        <h1><strong>Secret World</strong></h1>
  
    </div>
    <div class="col">
  
      <h3><strong>Cüzdan : 1550 Dinar</strong></h3>
  
    </div>
  
  </div>
  
  <br><br>

  <div class="card" style="width: 75rem; border-color: gold;">
    <div class="card-body">
      <h5 class="card-title">3. Bölüm</h5>
      <h5 class="card-title"><strong>Turnuva</strong></h5>
      <img src="{% static 'adventureapp/turnuva.jpg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
      <ol>
      <p class="card-text">Şehre gelen Katara şehirde de geçireceği günleri düşünerek 800 dinarlık hem dayanıklı hem de hareketini kısıtlamayan bir zırh aldı.</p>
      <p class="card-text">Bu şehirdeki turnuvada toplamda 32 kişiden oluşup 5 tur sürecektir.</p>
      <p class="card-text">Bu turnuvada bayılan , ölen veya sınır çizgisini geçen kişi kaybetmiş sayılacaktır ve kazanan ise her tur belli bir tutar ödül alacaktır.</p>
      <p class="card-text">1. olan kişi ise 20.000 dinar para ödülü alacaktır.</p>
      </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: gold;">
    <div class="card-body">
        <img src="{% static 'adventureapp/poisen.jpeg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
        <ol>
      <p class="card-text">Bu turnuvada garanti çeyrek finale çıkacağı düşünülen toplam 6 kişi var. Bunlar arasında en göze çarpan kişi İzumi adında soğuk bakışlı bir kızdı.</p>
      <p class="card-text">İlk etapta Katara'nın karşısına zırhına güvenen biri vardı ama ağır zırhı yüzünden yavaş hareket edebilen birisiydi.</p>
      <p class="card-text">Katara hızlı bir şekilde bir yara verdiğinde ilk rakibi birden yere düştü ve bayıldığını sanan Katara rakibinin öldüğünü görünce dehşete düşmüştü.</p>
      <p class="card-text">Katara bu kılıcın gücünden korkmuş olsa bile bu kılıcın gücü sayesinde hızlı bir şekilde ilk turu geçti.</p>
      </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: gold;">
    <div class="card-body">
        <img src="{% static 'adventureapp/karşılaşmaiki.jpg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
        <ol>
      <p class="card-text">Katara ilk turdan sonra ilk rakibinin ne yüzünden öldüğünü merak etmiş ve gecenin sonunda kılıcın zehirli olduğunu ve rakibinin o yüzden hızlıca öldüğünü anlamıştı.</p>
      <p class="card-text">Katara'nın ikinci turdaki rakibi aynı Katara gibi hafif zırhlı ve kılıç kabiliyetine güvenen birisiydi.</p>
      <p class="card-text">Rakibi Katara'nın ilk etabını izlediği için sıyrık bile almamaya çalışıyordu ve Katara'nın hep bir açığını arıyordu.</p>
      <p class="card-text">Rakibi Katara'nın vuruşlarını iyi okumaya başlamış ve bunu leyhine kullanıyordu.</p>
      <p class="card-text">Katara rakibinin kaçma hamlelerini okumaya çalışarak onu çizgi dışına çıkarmayı hedefliyordu ve bunu hızlı ama basit saldırılarla yapmayı amaçlıyordu.</p>
      <p class="card-text">Rakibi hızlı ve kıvrak bir saldırıyla boynunu kesmeye çalışırken Katara öleceğini düşünüp kılıcını çaresizlikle salladığında kılıcın verdiği zehir dalgası ile rakibi hızlıca ölürken Katara'da olayların etkisi ile bayılır.</p>
      </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: gold;">
    <div class="card-body">
        <img src="{% static 'adventureapp/room.webp' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
        <ol>
      <p class="card-text">Katara yavaş yavaş gözlerini açtığında hastanenin tavanını yanında ise tanıdık bir yüz , İzumi'yi görür.</p>
      <p class="card-text">Katara ona bu kılıcı nasıl bulduğunu anlatır ve ne yapcağını bilemediğini sorar.</p>
      <p class="card-text">İzumi'de buraya katılan herkesin zaten ölme ihtimalini kabullenerek geldiğini ve içini biraz rahat tutması gerektiğini söyler.</p>
      <p class="card-text">Katara'da nasıl bu kadar soğukkanlı olduğunu merak ettiğini söyleyince İzumi ona bu özelliğinin nedeninin bir sır olduğunu ve anlatamayacağını söyler.</p>
      <p class="card-text">Katara'da madem anlatmıyosun bari beraber antrenman yapmaya izin ver deyince İzumi' de peki madem der.</p>
      <p class="card-text">İzumi'de antrenman yerinin ilk karşılaştığımız ormanlık alan mı yoksa turnuva alanından uzak bir yerdeki büyük park mı diye sorar.</p>
      </ol>
      <a href="{% url 'adventureapp:forest' %}" class="btn btn-danger">Ormanlık Alan</a>
      <a href="{% url 'adventureapp:park' %}" class="btn btn-danger">Büyük Park</a>
    </div>
  </div>

<br>

{% endblock %}

adventureapp/templates/adventureapp/homepage.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="row">

    <div class="col"></div>
    <div class="col">

        <h1><strong>Secret World</strong></h1>

    </div>
    <div class="col">

      <h3><strong>Cüzdan : 50 Dinar</strong></h3>

    </div>

</div>

<br><br>

<div class="card" style="width: 75rem; border-color: blue;">
    <div class="card-body">
      <h5 class="card-title">1. Bölüm</h5>
      <h5 class="card-title"><strong>Taze Başlangıç</strong></h5>
      <img src="{% static 'adventureapp/solucan.jpeg' %}" class="card-img-top" alt="..." style="width: 65rem ; height: 30rem;">
      <ol>
      <p class="card-text">Yağmurlu bir günde yoldan geçen tüccar arabası hızlı bir şekilde en yakın köye varmayı çalışıyodur.</p>
      <p class="card-text">Hava yavaş yavaş açılmaya başlamıştı ki yer sallanmaya başladı.</p>
      <p class="card-text">Sallanmalar ciddi şekilde artmıştı ki yerden büyük bir solucana benzeyen bir canavar çıkmış ve tüccar arabasındakiler de korkmuş bir şekilde donakalmıştı.</p>
    </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: blue;">
  <div class="card-body">
    <img src="{% static 'adventureapp/kılıç.jpeg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
    <ol>
    <p class="card-text">Canavar solucan tüccar arabasına doğru hızlı bir şekilde yaklaşırken bir kılıcın kınından çıkma sesi duyuldu.</p>
    <p class="card-text">Canavar solucan tam tüccar arabasına dişini geçirecekken bir anda kafası kesildi.</p>
    <p class="card-text">Olanları hayretler içinde izleyen tüccarlar canavar solucanın kafasını kesen kişinin 16 yaşında bir genç olduğunu gördü.</p>
    </ol>
  </div>
</div>

<br>

<div class="card" style="width: 75rem; border-color: blue;">
  <div class="card-body">
    <img src="{% static 'adventureapp/yol.jpeg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
    <ol>
    <p class="card-text">Kılıcı canavarın sert etinden dolayı kırılan genç tüccarlara heyecanlı bir şekilde kendi isminin Katara olduğunu söyledi ve büyük bir turnuva düzenlenen şehrin nerede olduğunu sordu.</p>
    <p class="card-text">Tüccarlar şehrin nerede olabileceğini anlattıktan sonra orda yeni ve keskin kılıç bulabileceğini öğrendi.</p>
    <p class="card-text">Bu haberden ve tüccarları canavardan koruduğu için aldığı ödülden sonra yola koşturarak devam etti</p>
    </ol>
  </div>
</div>

<br>

<div class="card" style="width: 75rem; border-color: blue;">
  <div class="card-body">
    <img src="{% static 'adventureapp/ayrım.jpeg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
    <ol>
    <p class="card-text">Yola doğru koştururken bir anda duran Katara bir yol ayrımına gelmişti. Bu iki yol da şehre ulaşıyordu.</p>
    <p class="card-text">Sağdaki yol önünde kurumuş kandan bile tehlikeli yol olduğu belli oluyordu.</p>
    <p class="card-text">Soldaki yol bir çiçek bahçesi gibi koktuğundan insana huzur veren bir yapısı vardı.</p>
    </ol>
    <a href="{% url 'adventureapp:rightpath' %}" class="btn btn-danger">Sağ Yol</a>
    <a href="{% url 'adventureapp:leftpath' %}" class="btn btn-danger">Sol Yol</a>
  </div>
</div>

<br>

{% endblock %}

adventureapp/templates/adventureapp/leftpath.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="row">

  <div class="col"></div>
  <div class="col">

      <h1><strong>Secret World</strong></h1>

  </div>
  <div class="col">

    <h3><strong>Cüzdan : 1550 Dinar</strong></h3>

  </div>

</div>

<br><br>

<div class="card" style="width: 75rem; border-color: red;">
    <div class="card-body">
      <h5 class="card-title">2. Bölüm</h5>
      <h5 class="card-title"><strong>Ayırılan Yollar</strong></h5>
      <img src="{% static 'adventureapp/ağaç.webp' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
      <ol>
      <p class="card-text">Katara kılıcının da olmaması nedeniyle sola doğru gitmeyi mantıklı bulmuştu.</p>
      <p class="card-text">Her renkten çiçeklere bakarak ve çiçekleri koklayarak gelen Katara yorulmaya başlamıştı.</p>
      <p class="card-text">Çiçeklerle dolu bir yerde sadece bir tane ağaç olduğunu gören Katara onun altında oturarak uyuyakalmıştı.</p>
      <p class="card-text">Uyandığındaysa gördüğü şeye çok şaşırmıştı.</p>
      </ol>
    </div>
  </div>

<br>

  <div class="card" style="width: 75rem; border-color: red;">
    <div class="card-body">
        <img src="{% static 'adventureapp/kaya.webp' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
        <ol>
      <p class="card-text">Uyandığında bütün çiçekler solmuş ve altında oturduğu ağaçtaysa sadece dalları kalmıştı.</p>
      <p class="card-text">Olanlara anlam veremeyen Katara hızlı bir şekilde yoluna devam etmeye karar vermişti.</p>
      <p class="card-text">Katara yoluna devam ederken bir anda tiz bir ses duymuştu ve o ses hızlıca yaklaşıyordu.</p>
      <p class="card-text">Gelen şeyin ne olduğunu anlamak isteyen Katara bir kayanın arkasından gözetliyordu.</p>
      </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: red;">
    <div class="card-body">
        <img src="{% static 'adventureapp/ejderha.jpg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
        <ol>
      <p class="card-text">Gelen şey tiz sesine rağmen koca cüsseli bir ejderhaydı ve burdaki çiçeklerin ve ağacın enerjisini sömüren şey o gibi gözüküyordu.</p>
      <p class="card-text">Şu an kılıcının da olmaması sebebiyle ejderha onu görürse işinin biteceği kesindi o yüzden o geçene kadar Katara orda bekledi.</p>
      <p class="card-text">Ordan uçarak geçtikten sonra yoluna devam eden Katara'nın kafasında tek birşey vardı:Bir kılıç.</p>
      <p class="card-text">Katara devam ederken yavaştan şehirin duvarları görünmeye başlamıştı.</p>
      </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: red;">
    <div class="card-body">
    <img src="{% static 'adventureapp/bluekatana.jpg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
        <ol>
      <p class="card-text">Duvarlara doğru yaklaşırken Katara şehrin hemen yanındaki köye varmıştı.</p>
      <p class="card-text">Bu köyde han , çeşitli tüccarlar gibi bir sürü dükkan vardı.</p>
      <p class="card-text">Katara dükkanlara baka baka ilerlerken kılıç ve zırh satan bir tüccarın dükkanını görmüştü.</p>
      <p class="card-text">O dükkanda çeşitli kılıçlar arasından Katara'nın dikkatini çeken kılıç keskin , mavi saplı ve süslü bir kına sahipti ama neredeyse bütün parasını vermesi gerekiyordu.</p>
      </ol>
      <a href="{% url 'adventureapp:blue' %}" class="btn btn-danger">Katanayı Al</a>
      <a href="{% url 'adventureapp:safe' %}" class="btn btn-danger">Katanayı Alma</a>
    </div>
  </div>

<br>

{% endblock %}

adventureapp/templates/adventureapp/rightpath.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="row">

  <div class="col"></div>
  <div class="col">

      <h1><strong>Secret World</strong></h1>

  </div>
  <div class="col">

    <h3><strong>Cüzdan : 1550 Dinar</strong></h3>

  </div>

</div>

<br><br>

<div class="card" style="width: 75rem; border-color: red;">
    <div class="card-body">
      <h5 class="card-title">2. Bölüm</h5>
      <h5 class="card-title"><strong>Ayırılan Yollar</strong></h5>
      <img src="{% static 'adventureapp/orman.jpeg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
      <ol>
      <p class="card-text">Katara kendine güven vererek sağ yolu seçmiş ve yolda ilerlerken gördüğü iskeletlerle içine bir ürperti gelmişti.</p>
      <p class="card-text">Yol ormanlarla doluyken birden açık bir alana çıkmıştı.</p>
      <p class="card-text">Açık alanda hızlı ilerleyen bir silüet dikkatle giden bir şövalyenin kafasını 2 saniyede kesmişti.</p>
      </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: red;">
    <div class="card-body">
      <img src="{% static 'adventureapp/silüet.jpg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
      <ol>
      <p class="card-text">Bu olanlar karşısında irkilen Katara hemen yanındaki ağaca saklanarak silüetin nerde olduğunu kestirmeye çalıştı.</p>
      <p class="card-text">Görüş alanında silüeti göremeyen Katara bir anda ensesinde soğuk bir çelik hisssetti.</p>
      <p class="card-text">Kılıcı tutan kişinin sesi ona "Sakince arkanı dön." diyordu.</p>
      <p class="card-text">Arkasını döndüğü gibi soğuk bakışlı bir kızın ona katana tuttuğunu gördü.</p>
      </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: red;">
    <div class="card-body">
    <img src="{% static 'adventureapp/katana.jpg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
    <ol>
      <p class="card-text">Katara durumdan bir çıkış noktası bulamıyordu ki kız katanasını yavaşça indirdi ve kınına soktu.</p>
      <p class="card-text">Şaşkınca bakan Katara sebebini sorduğunda silahsız birine saldırmak istemediğini söyledi.</p>
      <p class="card-text">Katara ona turnuvaya gideceğini ve orda onla kapışmak istediğini söyledi.</p>
      <p class="card-text">Tam kız gidecekken Katara son olarak ismini söylemesini isteyince kız isminin İzumi olduğunu söyledi.</p>
    </ol>
    </div>
  </div>

<br>

<div class="card" style="width: 75rem; border-color: red;">
    <div class="card-body">
    <img src="{% static 'adventureapp/greenkatana.jpg' %}" class="card-img-top" alt="..." style="width: 65rem; height: 30rem;">
        <ol>
      <p class="card-text">Katara kendine gelene kadar biraz dinlenmiş ve durumunu tekrar gözden geçirmişti.</p>
      <p class="card-text">İzumi'nin ondan daha hızlı ve güçlü olduğu gün gibi ortadaydı ve bu durumla nasıl yüzleşeceğini bilmiyordu.</p>
      <p class="card-text">Orda kara kara düşünürken gözünü kamaştıran bir ışık görmüştü ki ışığın kaynağının İzumi'nin kadar olmasa da iyi bir katana olduğunu gördü.</p>
      <p class="card-text">Katananın yeşil renkli olması ve biraz tuhaf kokması Katara'yı düşündürmüştü.</p>
        </ol>
      <a href="{% url 'adventureapp:green' %}" class="btn btn-danger">Katanayı al</a>
      <a href="{% url 'adventureapp:safe' %}" class="btn btn-danger">Katanayı alma</a>
    </div>
  </div>

<br>

{% endblock %}